# Generated by Django 2.1.4 on 2022-11-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChoLon', '0003_auto_20221111_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pName', models.CharField(max_length=255)),
                ('pPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pQuantity', models.DecimalField(decimal_places=0, max_digits=3)),
                ('pDesc', models.TextField()),
                ('pDateCreated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('-pDateCreated',),
            },
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='first_name',
            new_name='fName',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='last_name',
            new_name='lName',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
    ]
